# Generated by Django 5.0.7 on 2024-08-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Полное имя автора",
                    ),
                ),
                (
                    "date_of_birth",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "date_of_death",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Дата смерти"
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True, null=True, verbose_name="Биография писателя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
