# Generated by Django 5.0.7 on 2024-07-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author'),
        ('books', '0002_book_bookstatus_delete_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
