# Generated by Django 5.0.7 on 2024-08-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название книги"),
                ),
                (
                    "written_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="год написание книги"
                    ),
                ),
                ("genre", models.CharField(max_length=100, verbose_name="Жанр книги")),
                (
                    "author",
                    models.ForeignKey(
                        max_length=100,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authors.author",
                        verbose_name="Автор книги",
                    ),
                ),
            ],
            options={
                "verbose_name": "книга",
                "verbose_name_plural": "книги",
            },
        ),
        migrations.CreateModel(
            name="BookStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступна"),
                            ("borrowed", "Занята"),
                            ("lost", "Потеряна"),
                        ],
                        max_length=100,
                        verbose_name="Статус книги",
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата выдачи киниги"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возвращение книги"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
            options={
                "verbose_name": "статус книги",
                "verbose_name_plural": "статусы книг",
            },
        ),
    ]
