# Generated by Django 5.0.7 on 2024-07-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название книги')),
                ('written_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата написание книги')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр книги')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('borrowed', 'Занята'), ('lost', 'Потеряна')], default='available', max_length=100, verbose_name='Статус книги')),
                ('author', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='authors.authors', verbose_name='Автор книги')),
            ],
        ),
    ]
