# Generated by Django 5.0.7 on 2024-08-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookstatus",
            name="taken_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выдачи киниги"
            ),
        ),
    ]
