# Generated by Django 5.0.7 on 2024-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_written_date_book_written_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstatus',
            old_name='issued_at',
            new_name='taken_at',
        ),
        migrations.AlterField(
            model_name='bookstatus',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возвращение книги'),
        ),
    ]
